### ISSUE TITLE
ValueError and AttributeError

### ISSUE THREAD

**Issue by huhuhud** [zdou0830/METER#22]
Hi,
I‘m trying to making "run.py" work for Pre-training, but I got ValueError and AttributeError, and I didn't find a solution, can you help me to check it? Thank you very much!

Traceback (most recent call last):
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "run.py", line 20, in main
    dm = MTDataModule(_config, dist=True)
  File "/home/T3090U3/PycharmProjects/hxf/METER/METER-main/meter/datamodules/multitask_datamodule.py", line 19, in __init__
    self.dm_dicts = {key: _datamodules[key](_config) for key in datamodule_keys}
  File "/home/T3090U3/PycharmProjects/hxf/METER/METER-main/meter/datamodules/multitask_datamodule.py", line 19, in <dictcomp>
    self.dm_dicts = {key: _datamodules[key](_config) for key in datamodule_keys}
  File "/home/T3090U3/PycharmProjects/hxf/METER/METER-main/meter/datamodules/coco_caption_karpathy_datamodule.py", line 7, in __init__
    super().__init__(*args, **kwargs)
  File "/home/T3090U3/PycharmProjects/hxf/METER/METER-main/meter/datamodules/datamodule_base.py", line 60, in __init__
    self.tokenizer = get_pretrained_tokenizer(tokenizer)
  File "/home/T3090U3/PycharmProjects/hxf/METER/METER-main/meter/datamodules/datamodule_base.py", line 25, in get_pretrained_tokenizer
    return RobertaTokenizer.from_pretrained(from_pretrained)
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1672, in from_pretrained
    resolved_vocab_files[file_id] = cached_path(
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/transformers/file_utils.py", line 1271, in cached_path
    output_path = get_from_cache(
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/transformers/file_utils.py", line 1494, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 16, in <module>
    def main(_config):
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/sacred/experiment.py", line 190, in automain
    self.run_commandline()
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/sacred/experiment.py", line 347, in run_commandline
    print_filtered_stacktrace()
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/sacred/utils.py", line 493, in print_filtered_stacktrace
    print(format_filtered_stacktrace(filter_traceback), file=sys.stderr)
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/sacred/utils.py", line 528, in format_filtered_stacktrace
    return "".join(filtered_traceback_format(tb_exception))
  File "/home/T3090U3/anaconda3/envs/hxf/lib/python3.8/site-packages/sacred/utils.py", line 568, in filtered_traceback_format
    current_tb = tb_exception.exc_traceback
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'

**Comment by zdou0830** [comment]
Hi, I'm not sure if this is because of the Internet connection issue as suggested. I think one way to get around it is to first download the pretrained tokenizers and weights from huggingface and then store it in the huggingface cached directory.

**Comment by huhuhud** [comment]
Sorry to bother you again. My text encoder selects “text_ Roberta”, so I downloaded "Roberta base" in the hugging face, and then made the changes in the following figure in the "meter_module.py" file, but the previous error will still be reported. Is it the wrong change I made? Or do I need to change something else? The command I run is "Python run.py with data_root=/home/t3090u3/pycharmprojects/hxf/meter/meter-main/meter/datasets/data num\u gpus=8 num\u nodes=1 task\u mlm\itm\clip\bert per\gpu batchsize=32 clip16 text\u Roberta image\u size=224”


Error:









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zdou0830/METER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月16日(星期四) 凌晨0:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zdou0830/METER] ValueError and AttributeError (Issue #22)





 
Hi, I'm not sure if this is because of the Internet connection issue as suggested. I think one way to get around it is to first download the pretrained tokenizers and weights from huggingface and then store it in the huggingface cached directory.

**Comment by zdou0830** [comment]
Hi, this issue seems related https://github.com/huggingface/transformers/issues/10901. not sure if it will help

**Comment by Kqp1227** [comment]
Maybe change to python3.7 works
